### ISSUE TITLE
The addon will not be compatible with ofx 0.10.0 in windows

### ISSUE THREAD

**Issue by gorkacortazar** [robotconscience/ofxLibwebsockets#104]
With the last release candidates of ofx 0.10.0 this addon was rendered incompatible, mostly because ofx upgraded the openSSL version to 1.1, which creates compilation conflicts the with current version of libwebsocket.

The current problems that we have identified:
- VS2017 now doesn't compile with the current version, as the openssl version is incompatible with the version of libwebsockets, the errors are the same that they describe here: https://github.com/warmcat/libwebsockets/issues/970
- Since RC1 openframeworks in linux, openssl is not included by default in the compilation, so is required to add the flags manually in qt creator at least. This most likely can be solved with small modifications addon_config.mk. I will be testing what happens with the current RC3 today.
- As ofx 0.10.0 includes ofJson, it will be ideal to remove the jsoncpp dependency. The inside working is slightly different, but took em one day to update our apps that were relying on ofxJson, which was also based on jsoncpp.

I'll continue to do more research and test on this and keep you posted if we manage to update some solutions, as our applications relies heavily on your addon, so we are more than glad to help.

**Comment by gorkacortazar** [comment]
I just noticed that in linux it compiles properly, as openframeworks does not link openssl anymore in this platform automatically, as long as you add the proper system flags to addon_config.mk

> ADDON_LDFLAGS = -lssl
> ADDON_LDFLAGS += -lcrypto

This is because Ubuntu include 1.0.x instead of 1.1, at least unit 18.04 that will be released tomorrow. Any suggestions on which strategy to explore will be welcomed

**Comment by robotconscience** [comment]
Hey @gorkacortazar, sorry for the delay in replying. Let me know if you've had a chance to investigate! Unfortunately I'm not able to devote much time to the addon anymore. Looking now at some OF 0.10 stuff, and it will likely break across most platforms... 

Keep me posted, and I'll let you know where I get! The trickiest thing will be where libwebsockets moves to openssl 1.1, as they did a pretty extensive API overhaul that will require a lot of work. 🤞

**Comment by gorkacortazar** [comment]
Hey @robotconscience currently I had to stop my research, but my findings are as follows. As the migration for the openssl is complex, the situation is fragmented depending on the platforms. recent versions of libwebsockets allows to compile with support of either version of the openssl api. As per ofx
- Ofx 0.10 on VS 2017 compiles openssl 1.1, wich makes the addon unusable. I tried to recompile it but didn't have too much time to test why the first try didn't work, I think that the API of libwesockets has changed a lot too.
- In linux es complex too, as ofx use the openssl included in the system. In 16.04 is good for the current addon,, but in Ubuntu 18.04 we will get the same problem, uses opnessl 1.1.

Also we found a bug in the addon that we couldn't figure out how to solve it. When a client is s connected sometimes disconnects, but is impossible to reconnect it again. Seems like the context of the websocket library is not fully destroyed, and try to explicitly connect again fails, but also trying to explicitly disconnect and trying con to connect again does nothing. Only happens when you are acting as a client, not a s a server. We spent a couple of weeks and we had to move on to finish a project, but I plan to get back to both issues in a couple of weeks.

**Comment by gorkacortazar** [comment]
The last commits in the repo works well in Widnows 10 and Ubuntu 16 (with openframeworks 0.10.0), but not in ubuntu 18 (because a different version of OpenSSL). It can be fixed with the following steps (may help the rpi issues too):

1. Clone libwebsockets source: https://github.com/warmcat/libwebsockets.git
2. Checkout the tag v1.4-chrome43-firefox-36
3. open the file libs/ssl.c
4. search the calls to ERR_remove_thread_state (there are two)
5. Replace the full #if block with this code: 
`#if (OPENSSL_VERSION_NUMBER < 0x10100000) #if (OPENSSL_VERSION_NUMBER <= 0x1000106f) || defined(USE_WOLFSSL) ERR_remove_state(0); #else #if OPENSSL_VERSION_NUMBER >= 0x1010005f && !defined(LIBRESSL_VERSION_NUMBER) && defined(OPENSSL_IS_BORINGSSL) ERR_remove_thread_state(); #else ERR_remove_thread_state(NULL); #endif #endif #endif
`
Compile the library with the instructions int he readme

**Comment by gorkacortazar** [comment]
Closing this as the last merged pull request works in ubuntu16

**Comment by KondakovArtem** [comment]
Hi. I am Trying to build example_client_hello_world on version 0.11.0 (Windows 7, Visual Studio 2019), I get the following error.
And it looks like I'm getting the same error

![image](https://user-images.githubusercontent.com/12134542/79082392-48b4d680-7d2e-11ea-9e09-ad056bff90ad.png)

Please tell me, for version >OF 0.9.8 is there a working solution?
